### ISSUE TITLE
Use of <i> in example

### ISSUE THREAD

**Issue by r12a** [w3c/unicode-xml#15]
Raised on 2013-01-18
By Richard Ishida

5.2 Generating New Text
http://www.w3.org/TR/unicode-xml/#Generating

"For example to write hello, one should use `<i>hello</i>` and not the sequence of Unicode characters U+210E, U+212F, U+2113, U+2113, U+2134."

Not a good example. The i tag should not be used merely for presentation according to HTML5. At least we should mention CSS styling.

**Comment by duerst** [comment]
Addressed by commits 669df07283b and 69997e34e.
